import Head from 'next/head'
import styles from './styles/array.module.css'
import Footer from './components/Footer'
import Layout from './components/Layout'
import React, {Component} from 'react'

var newArr = [];
class Array extends Component {

    arrays = e => {
      console.log('evento array');
        if(e.keyCode === 13){
      newArr = [];
      newArr.push(document.getElementById("input").value)
      const make = newArr;
      console.log(make);
        }
    }
    render(){
    return (
    <div className={styles.container}>
      <Head>
        <title>Arrays exemplos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout />
        <main className={styles.main}>
        <h1 className={styles.title}>
          Bem Vindo ao Exemplo de Arrays
        </h1>

        <tr className={styles.grid}>
          <td className={styles.card}>
             <p>Array separado por vírgulas (1,2,3,4,5) :&nbsp;&nbsp;</p>
          </td>
          <td className={styles.card}>
            <input id="input" type="text" onKeyDown={((e) => this.arrays(e))} ></input>
          </td>
        </tr>

      </main>

      <footer>
       <Footer />
      </footer>
    </div>
  )
  }
};

export default Array;